Added Start Quiz button to dashboard page
sushantahujaa/react-app pull request #3
Opened 2018-12-28 10:20 UTC by mounika-puppala

2018-12-28 10:40 UTC, ahujasushant approved these changes

2018-12-28 13:46 UTC, manu29d requested changes

2018-12-28 13:46 UTC, manu29d commented on src/App.js
> +import { BrowserRouter as Router, Route, Link} from "react-router-dom";
Unused imported variable `Link`

2018-12-28 13:46 UTC, manu29d commented on src/dashboard/instructions.js
> +import React, { Component } from 'react';
rename file with upper case first letter `Instructions`

2018-12-28 13:46 UTC, manu29d commented on src/dashboard/startQuiz.js
> +import React, { Component } from 'react';
Rename file with upper case first letter and a descriptive name`StartQuizButton`

2018-12-28 15:10 UTC, sushantahujaa commented on src/dashboard/startQuiz.js
> +import { Link } from 'react-router-dom';
I already did the startquiz button component part. I think but it's cool we can merge this in.

2018-12-29 08:48 UTC, manu29d approved these changes

2018-12-29 08:49 UTC, merged